#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NearHspt.Droid.Resource", IsApplication=true)]

namespace NearHspt.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int aamylocation = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ambulance = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int docitsmall = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int EMS = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fng = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int help = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int smallhelp = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int techn = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int fng = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int icon_round = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int launcher_foreground = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int AppCompatDialogStyle = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainTheme_Base = 2130968578;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
